# dbt_project/profiles.yml - FINAL VERSION

football_analytics_platform:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '../dashboard/dbt.duckdb'

    prod:
      type: duckdb
      path: '/opt/airflow/dashboard/dbt.duckdb'