# models/staging/sources.yml
version: 2

sources:
  - name: raw_football_data
    description: "Source data from football-data.org API stored in S3"
    database: "{{ env_var('AWS_S3_BUCKET_NAME') }}" # Use the bucket name from .env
    schema: "raw/matches" # This is the folder path within the bucket
    tables:
      - name: "matches_json"
        # This config tells DuckDB how to read all the JSON files from the S3 folder
        external:
          location: "s3://{{ env_var('AWS_S3_BUCKET_NAME') }}/raw/matches/*.json"
          format: "json"