# models/marts/schema.yml
version: 2

models:
  - name: fct_matches
    description: "Fact table containing all finished football matches."
    columns:
      - name: match_id
        description: "The unique identifier for a match."
        tests:
          - unique
          - not_null

  - name: dim_teams
    description: "Dimension table for football teams."
    columns:
      - name: team_id
        description: "The unique identifier for a team."
        tests:
          - unique
          - not_null